// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0u45knB5pifApvQf0upAyMjmHrRCWDuE',
    appId: '1:360352380572:android:b5e510c5f02e48b1511f59',
    messagingSenderId: '360352380572',
    projectId: 'booking-ticket-8d7f1',
    storageBucket: 'booking-ticket-8d7f1.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy08NNysRAykjkGCy8ebF10t2U1DUtfcY',
    appId: '1:360352380572:web:03d9c9ba9879fa62511f59',
    messagingSenderId: '360352380572',
    projectId: 'booking-ticket-8d7f1',
    authDomain: 'booking-ticket-8d7f1.firebaseapp.com',
    storageBucket: 'booking-ticket-8d7f1.firebasestorage.app',
    measurementId: 'G-WGQS0K7MPW',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB73B-yA2aqT99BwZJ6WIy0_LmgHU6Flzk',
    appId: '1:360352380572:ios:5c45bdd3d02ef065511f59',
    messagingSenderId: '360352380572',
    projectId: 'booking-ticket-8d7f1',
    storageBucket: 'booking-ticket-8d7f1.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB73B-yA2aqT99BwZJ6WIy0_LmgHU6Flzk',
    appId: '1:360352380572:ios:5c45bdd3d02ef065511f59',
    messagingSenderId: '360352380572',
    projectId: 'booking-ticket-8d7f1',
    storageBucket: 'booking-ticket-8d7f1.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAy08NNysRAykjkGCy8ebF10t2U1DUtfcY',
    appId: '1:360352380572:web:d6c8c928f184fbba511f59',
    messagingSenderId: '360352380572',
    projectId: 'booking-ticket-8d7f1',
    authDomain: 'booking-ticket-8d7f1.firebaseapp.com',
    storageBucket: 'booking-ticket-8d7f1.firebasestorage.app',
    measurementId: 'G-N8YZ99Z73V',
  );

}